### ISSUE TITLE
Spine issue in op20n6-01.hrm

### ISSUE THREAD

**Issue by TianxueHu** [napulen/haydn_op20_harm#1]
Hi @napulen ,
Thanks for making this dataset! I'm working with op20n6-01.hrm, however, there seems to be a spline alignment issue in this file. I failed to use `extractx -s` in Humdrum. And it warns "Incorrect number of spines in interpretation record" when loading the file in VHV. It will be great if you could check on that!

Thanks,
Tess

**Comment by napulen** [comment]
Hi @TianxueHu,

Thanks for the report! I will check into this somewhere this week.

If I don't fix the issue by Thursday, please ping me again.

**Comment by napulen** [comment]
Hi @TianxueHu,

I couldn't replicate the issue with `extractx -s`. When I run that command, I don't get any feedback. I guess I need to read the code of `extractx` because I don't remember what it does. However, I think I could figure out the issue from the Verovio Humdrum Viewer's output. It's been corrected and it should be fixed now. Try it out and let me know if you still experience issues.

I'll wait for your feedback before closing the issue.

Thanks for the report!

**Comment by TianxueHu** [comment]
Hi @napulen,
Sorry for the late reply, the message is flooded in my emails. Thanks for fixing the issue and it works perfectly now! `extractx -s ` basically extracts certain spines in the file. For example `extractx -s '1,4,5' ` extracts the 1st, 4th, 5th spine. Thanks again and have a good day! :)
Best,
Tess
